# Generated by Django 3.1.7 on 2021-04-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='description',
            field=models.CharField(default='d', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cake',
            name='image',
            field=models.ImageField(default='image.jpg', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cake',
            name='price',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
